Features/6
DeathsGun/art pull request #9
Opened 2022-08-25 12:13 UTC by 3BOL

Close #6

2022-09-01 12:05 UTC, DeathsGun requested changes

2022-09-01 12:05 UTC, DeathsGun commented on provider/excel.go
> +	outputFile := outputDir + "\\" + startDate + ".xlsx"
Git dafür ne Methode namens `filepath.Join`

2022-09-01 12:05 UTC, DeathsGun commented on provider/excel.go
> +		}
Den Fehler kann man ignorieren: `_ = f.Close()`

2022-09-01 12:05 UTC, DeathsGun commented on provider/excel.go
> +	content := ""
nimm nen buffer `&buffer.Bytes`

2022-09-01 12:05 UTC, DeathsGun commented on provider/excel.go
> +		fmt.Println(err)
Return reicht

2022-09-07 06:49 UTC, DeathsGun commented on provider/excel.go
> +	content := ""
buffer := &bytes.Buffer{}
buffer.WriteString("Hello")
buffer.String()

2022-09-07 06:51 UTC, 3BOL commented on provider/excel.go
> +	content := ""
Fett

2022-09-07 08:26 UTC, DeathsGun approved these changes

2022-09-07 08:27 UTC, PKMNPlatin approved these changes

2022-09-07 08:27 UTC, merged